## Anyone a fan of bomber man?


Write-Host "                        .-."
Write-Host "                        '-'"
Write-Host "                        //"
Write-Host "               _..---._//"
Write-Host "             .' .`     '-."
Write-Host "            /__/          \      *"
Write-Host "           ====_____     __\     :"
Write-Host "          /#   #``` |   /()\    :    ..*"
Write-Host "          |#   #    |   \__/    : .''"
Write-Host "          \#___#____|      /   :::.. ."
Write-Host "           \______________|_...‰_: .. '*"
Write-Host "  ()       // /\||||)))))))      '   . ."
Write-Host ".( \_     \\_\//   _-'.'/        |   * .."
Write-Host "( )  |^|^|^|ooo/  _#\.//```_      |   . . ."
Write-Host "(_)_.'v|v|v|     / \#  \_ / '_  _'    . .  "
Write-Host "           | _ _/_/     /'./_-|`         . ."
Write-Host "           /#_#__""`-._ /#  \__)       .  .   "
Write-Host "           |__   ""-._ |##               . . ."
Write-Host "           |  ""|-""`-_/##              . .    "
Write-Host "           /""--\__.-|                       ."
Write-Host "           \-_.-<__ /                   .   ."
Write-Host "           /-_| /  \"
Write-Host "           \-_| \_-<.                        .  ."
Write-Host "           <_-/ <_.-\                    ."
Write-Host "           <_-|  |_.-|                        ."
Write-Host "      .----|   \__\  \                 ."
Write-Host "     |     .```   '.  \                       "
Write-Host "      .___/        \__/"